services:
  ctfd:
    build: .
    restart: always
    env_file:
      - .ctfd.env
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=${UPLOAD_FOLDER:-/var/uploads}
      - DATABASE_URL=${DATABASE_URL:-mysql+pymysql://ctfd:${DB_PASSWORD:-ctfd}@db/${DB_NAME:-ctfd}}
      - REDIS_URL=${REDIS_URL:-redis://cache:6379}
      - WORKERS=${WORKERS:-1}
      - LOG_FOLDER=${LOG_FOLDER:-/var/log/CTFd}
      - ACCESS_LOG=${ACCESS_LOG:--}
      - ERROR_LOG=${ERROR_LOG:--}
      - REVERSE_PROXY=${REVERSE_PROXY:-true}
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    depends_on:
      - db
      - cache
    networks:
      default:
      internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ctfd

  db:
    image: mariadb:10.11
    restart: always
    env_file:
      - .ctfd.env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-ctfd-root-change-me}
      - MARIADB_USER=${DB_USER:-ctfd}
      - MARIADB_PASSWORD=${DB_PASSWORD:-ctfd}
      - MARIADB_DATABASE=${DB_NAME:-ctfd}
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      internal:
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      internal:

networks:
  default:
  internal:
    internal: true
